[install]
state = enabled

[launcher]
author = Joe Hagan
description = Offline help.splunk.com documentation browser with Enterprise, ES8, SOAR, and ITSI
version = 0.4.12

[ui]
is_visible = 1
label = Splunk Offline Docs
show_in_nav = 1

[package]
id = splunk_offline_docs
check_for_updates = 0
build = 20260721f
