[script:offline_docs]
match = /offline_docs
script = offline_docs_handler.py
scripttype = persist
handler = offline_docs_handler.OfflineDocsHandler
requireAuthentication = true
output_modes = json
passPayload = true
passHttpHeaders = true
python.version = python3
capability.get = admin_all_objects
capability.post = admin_all_objects
